name: togo_getx
description: Store and Cart example using GetX in Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  gap: ^2.0.1
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  scrollable_positioned_list: ^0.3.5
  flutter_elegant_number_button: ^0.0.6
  badges: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase: ^1.2.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
